// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhjgcNhBFaCeqgKoMbCzc-OEJZJIcMJE4',
    appId: '1:924487955407:web:8e3bb172224655f3c858ba',
    messagingSenderId: '924487955407',
    projectId: 'mobifixapp',
    authDomain: 'mobifixapp.firebaseapp.com',
    storageBucket: 'mobifixapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgOGA8s5y76sGZhQF9czRDyUlr8HTXcNg',
    appId: '1:924487955407:android:6d7e1d32b384d961c858ba',
    messagingSenderId: '924487955407',
    projectId: 'mobifixapp',
    storageBucket: 'mobifixapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNzMFRXf96nLrxY9hRZPIWGgSPmexrRJs',
    appId: '1:924487955407:ios:53d0b6eed09904fac858ba',
    messagingSenderId: '924487955407',
    projectId: 'mobifixapp',
    storageBucket: 'mobifixapp.appspot.com',
    iosBundleId: 'com.example.mobiFix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNzMFRXf96nLrxY9hRZPIWGgSPmexrRJs',
    appId: '1:924487955407:ios:53d0b6eed09904fac858ba',
    messagingSenderId: '924487955407',
    projectId: 'mobifixapp',
    storageBucket: 'mobifixapp.appspot.com',
    iosBundleId: 'com.example.mobiFix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhjgcNhBFaCeqgKoMbCzc-OEJZJIcMJE4',
    appId: '1:924487955407:web:014074c89ac33b44c858ba',
    messagingSenderId: '924487955407',
    projectId: 'mobifixapp',
    authDomain: 'mobifixapp.firebaseapp.com',
    storageBucket: 'mobifixapp.appspot.com',
  );
}
